// Start with D (Data): Define your variables and data types.
// Move to V (Values): Use operators to manipulate your data.
// Implement L (Logic): Use control flow to make decisions and repeat actions.
// Organize with C (Code Blocks): Create functions for reusable code.
// Find the elements with F (Find): Use DOM manipulation to find the elements.
// React to E (Events): Add event listeners to trigger functions.
// Take A (Actions): Modify the DOM based on events and logic.
// Display R (Results): Output the final results.


let health = 100;
let coins = 0;
let gameIsActive = true;


// I started by declaring my variables and assigning values to them here I've created 3 variables here Health, Coins, and a true variable named gameIsActive

function rollDice() {
    const amount = Math.floor(Math.random() * 100);
    document.getElementById('diceAmount').innerHTML = amount;
    return amount;
}
// rollDice
// math.random() : generates the result of a random number between 0 and 1 (0.123)
// math.random() * 100 : this multiplies the number generated by 100 putting it in between 1 and 100 (12.3)
// math.floor(...)rounds the result from step 2 down to the nearest whole number (12)
// The result is now equal to the roll of a 100 sided dice 
// I wanted to tell the user what they rolled each time so I made the image of a 100 sided dice and put it as the background of a div then i put a div inside of it and made its position relative to the div for the img which a square fits nicely inside a triangle so that the value rolled can be displayed there. so Inside the rollDice funtion I have it access the element with the id diceamount the box inside the img box and have that = amount so it will always show the value of the roll after you click the button 

function rollFate() {
    if (!gameIsActive) return;
    // this if condition uses the not Operator and it means the opposite so if gameIsActive = true then !gameIsActive will equal false. so its asking it to check to see if gameIsActive is false and it returns the answer to the code that called it. 

    const roll = rollDice();
    let message =``;

    switch (true) {
            const damage = rollDice();
            health -= damage;
            message = `Oh no! You took ${damage} damage!`;
            document.getElementById('health').innerHTML = health;
            break;
        case roll >= 26 && roll <= 75:
            const treasure = rollDice();
            coins += treasure;
            message = `Wow you found ${treasure} treasure!`;
            document.getElementById('coins').innerHTML = coins;
            break;
        case roll >= 76 && roll <= 100:
            message = `Strange... nothing happened.`;
            break;
        default:
            message = `An unexpected error has occurred`;
            break;
    }

    document.getElementById('status').innerHTML = message;

    if (health <= 0) {
        gameOver("tryAgain");
    } else if (coins >= 100) {
        gameOver("playAgain");
    }
}

function gameOver(outcome) {
    gameIsActive = false;
    document.getElementById('status').innerHTML = outcome === "tryAgain" ? "You Lost! Try again?" : "You won! Play again?";

    document.getElementById('rollButton').onclick = function() {
        resetGame();
        rollFate();
    };
}

function resetGame() {
    if (health < 0) 
    health = 100;
    coins = 0;
    gameIsActive = true;
    document.getElementById('health').innerHTML = health;
    document.getElementById('coins').innerHTML = coins;
    document.getElementById('status').innerHTML = "Welcome to the Adventure encounter game! Roll the dice to start the game!";
    document.getElementById('diceAmount').innerHTML = "";
}